# Generated by Django 3.1.3 on 2020-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:/Users/HPESDC/PycharmProjects/try django/src/Django/Django/imgs')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
